/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.VitalSigns;
import model.VitalSignHistory;
/**
 *
 * @author Lenovo
 */
public class CreateJPanel extends javax.swing.JPanel {

   VitalSignHistory vitalSignHistory;
    
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(VitalSignHistory vitalSignHistory) {
        initComponents();
        this.vitalSignHistory = vitalSignHistory; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datelbl = new javax.swing.JLabel();
        BPlbl = new javax.swing.JLabel();
        templbl = new javax.swing.JLabel();
        pulselbl = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        BPtxt = new javax.swing.JTextField();
        temptxt = new javax.swing.JTextField();
        pulsetxt = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        titlelbl = new javax.swing.JLabel();

        datelbl.setText("Date");

        BPlbl.setText("Blood Pressure");

        templbl.setText("Temperature");

        pulselbl.setText("Pulse");

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        titlelbl.setText("CREATE VITALS ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulselbl)
                    .addComponent(templbl)
                    .addComponent(BPlbl)
                    .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(datetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addComponent(BPtxt)
                        .addComponent(temptxt))
                    .addComponent(pulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 185, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(savebtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(titlelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(titlelbl)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(templbl)
                    .addComponent(temptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BPlbl)
                    .addComponent(BPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulselbl)
                    .addComponent(pulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(savebtn)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        Double Temperature = Double.parseDouble(temptxt.getText());
        Double BloodPressure = Double.parseDouble(BPtxt.getText());
        int pulse = Integer.parseInt(pulsetxt.getText());
        String date = datetxt.getText();
    
    VitalSigns newVs = vitalSignHistory.addNewVitals();
            
            newVs.setTemperature(Temperature);
            newVs.setBloodpressure(BloodPressure);
            newVs.setPulse(pulse);
            newVs.setDate(date);
    
            JOptionPane.showMessageDialog(this,"New Vital Signs Created" ,"Success" , JOptionPane.INFORMATION_MESSAGE);
            
            temptxt.setText("");
            BPtxt.setText("");
            pulsetxt.setText("");
            datetxt.setText("");

    }//GEN-LAST:event_savebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BPlbl;
    private javax.swing.JTextField BPtxt;
    private javax.swing.JLabel datelbl;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel pulselbl;
    private javax.swing.JTextField pulsetxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel templbl;
    private javax.swing.JTextField temptxt;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
