/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VitalSignHistory;
import model.VitalSigns;
/**
 *
 * @author Lenovo
 */
public class ViewJPanel extends javax.swing.JPanel {

    VitalSignHistory vitalSignHistory;
    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(VitalSignHistory vitalSignHistory) {
        initComponents();
        this.vitalSignHistory = vitalSignHistory; 
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        templbl = new javax.swing.JLabel();
        pulselbl = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        BPtxt = new javax.swing.JTextField();
        temptxt = new javax.swing.JTextField();
        pulsetxt = new javax.swing.JTextField();
        datelbl = new javax.swing.JLabel();
        BPlbl = new javax.swing.JLabel();
        Viewdtslbl = new javax.swing.JButton();
        deleteVslbl = new javax.swing.JButton();
        Viewtitlelbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablevitals = new javax.swing.JTable();

        templbl.setText("Temperature");

        pulselbl.setText("Pulse");

        datelbl.setText("Date");

        BPlbl.setText("Blood Pressure");

        Viewdtslbl.setText("View Details");
        Viewdtslbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewdtslblActionPerformed(evt);
            }
        });

        deleteVslbl.setText("Delete Vitals");
        deleteVslbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVslblActionPerformed(evt);
            }
        });

        Viewtitlelbl.setText("VIEW VITALS ");

        tablevitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "TEMPERATURE", "BLOOD PRESSURE", "PULSE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablevitals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Viewdtslbl)
                .addGap(34, 34, 34)
                .addComponent(deleteVslbl)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Viewtitlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pulselbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BPlbl)
                                        .addComponent(templbl))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BPtxt)
                                        .addComponent(temptxt))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Viewtitlelbl)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Viewdtslbl)
                    .addComponent(deleteVslbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(templbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(temptxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BPlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BPtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulselbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pulsetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewdtslblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewdtslblActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tablevitals.getSelectedRow();
        
        
        if (selectedIndex >0){
            JOptionPane.showMessageDialog(this,"Please select a row first","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tablevitals.getModel(); 
        VitalSigns selectedVitals = (VitalSigns) model.getValueAt(selectedIndex, 0);
        
        if (selectedVitals != null){
            temptxt.setText(Double.toString(selectedVitals.getTemperature()));
            BPtxt.setText(Double.toString(selectedVitals.getBloodpressure()));
            pulsetxt.setText(Integer.toString(selectedVitals.getPulse()));
            datetxt.setText(selectedVitals.getDate());
        }
    }//GEN-LAST:event_ViewdtslblActionPerformed

    private void deleteVslblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVslblActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tablevitals.getSelectedRow();
        
        
        if (selectedIndex >0){
            JOptionPane.showMessageDialog(this,"Please select a row first","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tablevitals.getModel(); 
        VitalSigns selectedVitals = (VitalSigns) model.getValueAt(selectedIndex, 0);
        
        if (selectedVitals != null){
        vitalSignHistory.removeVitals(selectedVitals);
        JOptionPane.showMessageDialog(this,"Vitals Deleted","Success" ,JOptionPane.INFORMATION_MESSAGE);
    }
        
        populateTable();
    }//GEN-LAST:event_deleteVslblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BPlbl;
    private javax.swing.JTextField BPtxt;
    private javax.swing.JButton Viewdtslbl;
    private javax.swing.JLabel Viewtitlelbl;
    private javax.swing.JLabel datelbl;
    private javax.swing.JTextField datetxt;
    private javax.swing.JButton deleteVslbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pulselbl;
    private javax.swing.JTextField pulsetxt;
    private javax.swing.JTable tablevitals;
    private javax.swing.JLabel templbl;
    private javax.swing.JTextField temptxt;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tablevitals.getModel();   
        model.setRowCount(0);
        
        
        for (VitalSigns vs : vitalSignHistory.getHistory()){
        
            Object[] row = new Object[4];
            row[0] =vs  ;
            row[1] = vs.getTemperature();
            row[2] = vs.getBloodpressure();
            row[3] = vs.getPulse();
          
            model.addRow(row);
            
                    
        
        
        
        
        
            }
        }
}
